### ISSUE TITLE
主页添加病患接口

### ISSUE THREAD

**Issue by 2015wang** [stupid-coder/CurusSpring#2]
主页添加病患接口  
请求字段  
字段  是否必须    类型  说明
token   TRUE    string  token
code    TRUE    string  发送病患手机的验证码
phone   TRUE    string  病患手机号
id_number   TRUE    string  病患身份证号
appellation TRUE    string  称呼 可选self, zu, fu, tong, wan,分别代表祖,父,同,晚
name    TRUE    string  病患姓名
gender  TRUE    int 性别 1男 2女
brith   TRUE    string  生日
adress  FALSE   string  地址
weight  TRUE    string  体重（kg)
height  TRUE    string  身高（cm)
返回字段  
status      string  响应状态标志，1为请求成功,-1为有异常
patient_id      int 病患id

**Comment by stupid-coder** [comment]
OK
