### ISSUE TITLE
Quota 相关字段

### ISSUE THREAD

**Issue by stupid-coder** [stupid-coder/CurusSpring#28]

**Comment by 2015wang** [comment]
血糖指标中心-获取血糖接口  
请求字段  
字段名   是否必须    类型  备注
token   TRUE    string  token
patient_id  TRUE    string  病患的id
moment      string  血糖采集时刻，如果为空表示最近一次采集血糖的时间
lastest         获取最近多少天的该时刻血糖值
返回字段  
time    TRUE        血糖的采集日期
acmethods   TRUE    string  血糖采方式（指尖还是静脉）
bdsugarValue    TRUE    string  血糖值，正常为浮点数，超标为Hi值或低血糖

血糖测量时刻
空腹
早餐后2h
午餐前
午餐后2h
睡前
晚餐后2h
晚餐前
夜间

**Comment by 2015wang** [comment]
血糖指标中心-更新血糖接口  
请求字段  
字段名   是否必须    类型  备注
token   TRUE    string  token
patient_id  TRUE    string  病患的id
moment  TRUE    string  血糖采集时刻，如果为空表示最近一次采集血糖的时间
time    TRUE        血糖采集日期
acmethods   TRUE    string  血糖采方式（指尖还是静脉）
bdsugarValue    TRUE    string  血糖值，正常为浮点数，超标为Hi值或低血糖
返回字段  
statue      string  响应状态标志，1成功，-1异常

血糖测量时刻
空腹
早餐后2h
午餐前
午餐后2h
睡前
晚餐后2h
晚餐前
夜间

**Comment by 2015wang** [comment]
获取身体活动接口（07_录入_身体活动.png）  
请求字段  
字段名   是否必须    类型  说明
token   TRUE    string  token
patient_id  TRUE    string  病患的id
返回字段名  
statue      string  响应状态标志，1为请求成功,-1为有异常
date            最后一次录入时间
phactivity      string  运动量          ////需要根据提交的活动计算
value       list    运动项目列表
.sport_id       string  运动的id
.sport_value        int 参与运动的时间

**Comment by 2015wang** [comment]
膳食构成指标中心-获取膳食接口（07_录入_膳食构成.png)  
请求字段  
字段名   是否必须    类型  备注
token   TRUE    string  token
patient_id  TRUE    string  病患的id
返回字段  
statue      string  响应状态标志，1成功，-1异常
date            最新一次录入时间
score       int 当前得分
value       list    指标数据（展开如下）
.salt       string  盐摄入情况
.fruit      string  水果摄入情况
.vegetables     string  蔬菜摄入情况
.milk       string  牛奶摄入情况
.cereal     string  谷类摄入情况
.beans      string  豆类摄入情况
.meat       string  肉类摄入情况

当前得分需要根据提交情况进行计算
摄入情况分为五种 很多、多、一般、少、很少

**Comment by 2015wang** [comment]
饮食定量指标中心-获取饮食接口（07_录入_饮食定量.png)  
请求字段  
字段名   是否必须    类型  备注
token   TRUE    string  token
patient_id  TRUE    string  病患的id
返回字段  
statue      string  响应状态标志，1成功，-1异常
score       int 当前得分
date            最新一次录入时间
value       list    指标数据（展开如下）
.lunch      string  中餐为几成饱
.dinner     string  晚餐为几成饱
.snacks     string  一周吃零食的次数
.fatink     string  油脂摄入情况
饮食定量得分也需要根据录入情况计算
油脂摄入情况分为差别不大、偏高、偏低三个层次，具体怎么给你传你来定义即可
