### ISSUE TITLE
主页获取病患列表接口

### ISSUE THREAD

**Issue by 2015wang** [stupid-coder/CurusSpring#3]
主页获取病患列表接口  
请求字段  
字段名   是否必须    类型  说明
token   TRUE    string  token
返回字段名  
statue      string  响应状态标志，1为请求成功,-1为有异常
patients        list    所管理的病患列表
.patient_name       string  病患姓名
.role_name      string  用户对该病患的角色 super是关键管理员, common是普通管理员
.is_self        boolean 该病患是不是用户本人 true是 false为否
.patient_id     int 病患id
.appellation_name       string  称呼 self, zu, fu, tong, wan,分别代表本人,祖,父,同,晚

**Comment by stupid-coder** [comment]
OK
