### ISSUE TITLE
体重指标中心-获取体重接口

### ISSUE THREAD

**Issue by 2015wang** [stupid-coder/CurusSpring#7]
体重指标中心-获取体重接口（体重.png)  
请求字段  
字段名   是否必须    类型  备注
token   TRUE    string  token
patient_id  TRUE    string  病患的id
返回字段  
statue      string  响应状态标志，1成功，-1异常
data        dict    最近90天体重数据（有序，展开如下）
.w_date         日期
.w_value        string  体重

**Comment by stupid-coder** [comment]
请求字段

{
    "cate": "weight",  // 表示请求的指标类型
    "patient_id": "9",  
    "token": "52dfd271c4284ae3855a7203bc571cd1"
}

返回字段

{
    "data": [
        {
            "measure_time": 1454511691000, 
            "value": "100.0"
        }
    ], 
    "status": 1
}
