### ISSUE TITLE
体重指标中心-提交体重接口（更新体重）	

### ISSUE THREAD

**Issue by 2015wang** [stupid-coder/CurusSpring#8]
体重指标中心-提交体重接口（更新体重）  
字段名   是否必须    类型  备注
token   TRUE    string  token
patient_id  TRUE    string  病患的id
date    TRUE    数据类型    体重测量时间
weight  TRUE    float   病患的体重
返回字段  
statue      string  响应状态标志，1成功，-1异常

**Comment by stupid-coder** [comment]
请求接口：
{
    "cate": "weight",   // 指标类型
    "date": "1454743106",  // 提交的时间戳
    "patient_id": "9", 
    "token": "52dfd271c4284ae3855a7203bc571cd1", 
    "value": "120" //提交指标的值
}
